# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/corrosion_detection',
                'doc_host': 'https://justforprogramming07-code.github.io',
                'git_url': 'https://github.com/justforprogramming07-code/corrosion_detection',
                'lib_path': 'corrosion_detection'},
  'syms': {}}
